### ISSUE TITLE
Publish extension to Open VSX Registry

### ISSUE THREAD

**Issue by mtalexan** [google/selinux-policy-languages#2]
Microsoft limits what/who can publish and access the Microsoft Marketplace that provides the default store for VSCode extensions.  But an open registry exists, Open-VSX.org, that is compatible with non-Microsoft tools as well, like VSCodium.

Publishing to OpenVSX is very easy and there are even templates for GitHub actions to automate it.  Details can be found here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by qwandor** [comment]
Thanks for the suggestion! Looks like I need @ogiekako to give me access to the Google namespace on Open VSX, but once that's sorted I'll publish this and my other extensions there.

**Comment by qwandor** [comment]
Done: https://open-vsx.org/extension/Google/selinux-policy-languages
